# NumPy    

In [1]:
import numpy as np

## Numpy Array

In [2]:
lst = [1,2,3]

In [3]:
np.array(lst)

array([1, 2, 3])

## np.arange()

In [4]:
# Creating a numpy array using built-in generators

In [5]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [6]:
# np.arange( start_position, stop_position [non-inclusive], step_size )

## np.zeros() & np.ones()

In [7]:
# filling np.array with zeros

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
# np.array two-dimensional filled with zeros

In [10]:
np.zeros((5, 5)) # tuple with two-dimensional size specification # ( row_size, column_size)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
# np.array filled with ones

In [12]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
# np.array two-dimensional filled with ones should specify a tuple with dimensional sizes

In [14]:
np.ones((5,5)) # ( row_size, column_size)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## np.linspace ()

In [15]:
# np.array of all equi-distant (linearly spaced) points within given range can be obtained as follows

In [16]:
# np.linspace( start_position, stop_position [inclusive], Number of points/spaces)

In [17]:
np.linspace(0, 10, 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [18]:
np.linspace(1, 10, 9)

array([ 1.   ,  2.125,  3.25 ,  4.375,  5.5  ,  6.625,  7.75 ,  8.875,
       10.   ])

In [19]:
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

## np.eye()

In [20]:
# np.eye() is useful in creating identity matrices

In [21]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
# np.eye( square_matrix_dimension )

In [23]:
np.eye(1)

array([[1.]])

In [24]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

## np.random

In [25]:
np.random.randn(1) # normal distribution is used

array([1.21214144])

In [26]:
np.random.rand(5) # uniform distribution is used

array([0.70841742, 0.13566358, 0.71530206, 0.16270367, 0.24169157])

In [27]:
# np.random.rand[n] ( number_of_array_elements )

In [28]:
# producing two-dimensional array populated with random numbers

In [29]:
np.random.rand(5,5) # ( row_size, column_size)

array([[0.55878521, 0.83847631, 0.28919325, 0.41180923, 0.9452472 ],
       [0.39552046, 0.38144068, 0.9997495 , 0.17357259, 0.99806782],
       [0.24300091, 0.53511553, 0.81728509, 0.64057432, 0.31946537],
       [0.23513924, 0.43563934, 0.25142276, 0.86253197, 0.29203668],
       [0.06878073, 0.92242501, 0.2809744 , 0.26353777, 0.17078723]])

In [30]:
np.random.randn(2,2) # ( row_size, column_size)

array([[-0.35331164,  0.14062837],
       [ 2.71641759, -0.16529605]])

### np.random.randint

In [31]:
np.random.randint(10)

9

In [32]:
# one-argument   => maximum_limit
# two-argument   => lower_limit, maximum_limit
# three-argument => lower_limit, maximum_limit, number_of_random_numbers

In [33]:
np.random.randint(1, 10)

3

In [34]:
np.random.randint(1, 10, 4)

array([9, 7, 4, 8])

## np.array.reshape & np.array.shape

In [35]:
arr = np.arange(25)

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [37]:
arr.reshape(5,5) # (row_size , column_size)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
# reshape can only be used if number of elements in array can be represented as row_size x column_size

In [39]:
# np.array has a instance variable that stores the array's dimensional sizes in it.

In [40]:
arr.shape

(25,)

In [41]:
arr = arr.reshape(5,5)

In [42]:
arr.shape

(5, 5)

In [43]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

## Max. Min, Argmax, Argmin

In [44]:
arr.max() # maximum value in array

24

In [45]:
arr.min() # minimum value in array

0

In [46]:
arr.argmax() # index of the largest value in array

24

In [47]:
arr.argmin() # index of the smallest value in array

0

## NumPy Array Indexing and Slicing

In [48]:
arr = np.arange(11,21)

In [49]:
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [50]:
arr[0]

11

In [51]:
arr[9]

20

In [52]:
arr[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [53]:
arr[1:5] # [ start_position : stop_position (non_inclusive) ]

array([12, 13, 14, 15])

In [54]:
arr[-1] # negative-indexing also works

20

In [55]:
arr[::-1] # reversing the array using pythonic idioms

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11])

In [56]:
arr[::2] # [ : : step_size]

array([11, 13, 15, 17, 19])

## Numpy Array Broadcasting

In [57]:
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [58]:
arr[:] = 5 # changes all the elements in the array to 5

In [59]:
arr # broadcasting has affected all the elements in the array

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

## NumPy Array copies shallowly

In [60]:
arr = np.random.rand(10)

In [61]:
arr

array([0.2123286 , 0.53981783, 0.93447943, 0.48637746, 0.46641417,
       0.60683318, 0.55844138, 0.23811794, 0.1376223 , 0.02072225])

In [62]:
slice_arr = arr[:5]

In [63]:
slice_arr

array([0.2123286 , 0.53981783, 0.93447943, 0.48637746, 0.46641417])

In [64]:
# now changing the values of slice_arr will affect the original array

In [65]:
slice_arr[:] = 99

In [66]:
slice_arr

array([99., 99., 99., 99., 99.])

In [67]:
arr # original array is also changed

array([9.90000000e+01, 9.90000000e+01, 9.90000000e+01, 9.90000000e+01,
       9.90000000e+01, 6.06833179e-01, 5.58441378e-01, 2.38117942e-01,
       1.37622303e-01, 2.07222529e-02])

In [68]:
# This methodology of 'VIEW' of an array is utilized for preventing memory issues while working with large arrays

In [69]:
# slice_arr is an view of arr

In [70]:
# To make a new copy of data contents of an array, we use 'copy()' method built-in to array.

In [71]:
new_copy = arr.copy()

In [72]:
new_copy

array([9.90000000e+01, 9.90000000e+01, 9.90000000e+01, 9.90000000e+01,
       9.90000000e+01, 6.06833179e-01, 5.58441378e-01, 2.38117942e-01,
       1.37622303e-01, 2.07222529e-02])

In [73]:
arr

array([9.90000000e+01, 9.90000000e+01, 9.90000000e+01, 9.90000000e+01,
       9.90000000e+01, 6.06833179e-01, 5.58441378e-01, 2.38117942e-01,
       1.37622303e-01, 2.07222529e-02])

In [74]:
new_copy[:] = 100 # broadcasting to copied array doesn't affect the original array anymore

In [75]:
new_copy

array([100., 100., 100., 100., 100., 100., 100., 100., 100., 100.])

In [76]:
arr # original array remains unchanged

array([9.90000000e+01, 9.90000000e+01, 9.90000000e+01, 9.90000000e+01,
       9.90000000e+01, 6.06833179e-01, 5.58441378e-01, 2.38117942e-01,
       1.37622303e-01, 2.07222529e-02])

## NumPy Two-Dimensional Array

In [77]:
arr2d = np.array([[10,12],[13,14]]) # passing a list of list as argument creates a 2D array

In [78]:
arr2d

array([[10, 12],
       [13, 14]])

In [79]:
# 2D Array indexing can be done two ways

In [80]:
# 1. By normal, Two bracket notation => [row_index] [column_index]

In [81]:
# 2. Using single bracket with comma separated values => [ row_index , column_index ]

In [82]:
# Method 1
arr2d[0][1] # Two-Bracket Method

12

In [83]:
# Method 2
arr2d[0,1] # Comma-Separated Method

12

### Accessing Sub-Matrices

In [90]:
arr2d = np.array([np.random.rand(10), np.random.rand(10)])

In [91]:
arr2d

array([[0.23730239, 0.63950289, 0.39008715, 0.41825881, 0.39092049,
        0.1857469 , 0.67698653, 0.71155122, 0.76527403, 0.27404483],
       [0.46435389, 0.76267117, 0.96230907, 0.98305962, 0.37408563,
        0.90918674, 0.42199046, 0.28617196, 0.73771635, 0.93677071]])

In [92]:
arr2d[:,:]

array([[0.23730239, 0.63950289, 0.39008715, 0.41825881, 0.39092049,
        0.1857469 , 0.67698653, 0.71155122, 0.76527403, 0.27404483],
       [0.46435389, 0.76267117, 0.96230907, 0.98305962, 0.37408563,
        0.90918674, 0.42199046, 0.28617196, 0.73771635, 0.93677071]])

In [93]:
arr2d[:1, :5] # Obtain a Sub-Matrix containing 1st Row and First 5 Column

array([[0.23730239, 0.63950289, 0.39008715, 0.41825881, 0.39092049]])

In [95]:
arr2d = arr2d.reshape(5,4)

In [96]:
arr2d.shape

(5, 4)

In [98]:
arr2d

array([[0.23730239, 0.63950289, 0.39008715, 0.41825881],
       [0.39092049, 0.1857469 , 0.67698653, 0.71155122],
       [0.76527403, 0.27404483, 0.46435389, 0.76267117],
       [0.96230907, 0.98305962, 0.37408563, 0.90918674],
       [0.42199046, 0.28617196, 0.73771635, 0.93677071]])

In [97]:
# selecting determinant matrix for first element in arr2d
arr2d[1: , 1:]

array([[0.1857469 , 0.67698653, 0.71155122],
       [0.27404483, 0.46435389, 0.76267117],
       [0.98305962, 0.37408563, 0.90918674],
       [0.28617196, 0.73771635, 0.93677071]])